import React from 'react';
import { BarChart3, CircleAlert, Ship, Waves } from 'lucide-react';
import { mockIncidents, mockVessels } from '../data/mockMaritimeData';

export const AnalyticsView: React.FC = () => {
  const riskCounts = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((risk) => ({ risk, count: mockIncidents.filter((incident) => incident.risk === risk).length }));
  return <div className="p-3.5 sm:p-5 space-y-4 max-w-6xl mx-auto font-mono text-slate-100"><div className="border-b border-slate-800 pb-4"><div className="flex items-center gap-2"><BarChart3 className="w-5 h-5 text-cyan-400" /><h2 className="text-lg font-bold text-white">Maritime Analytics</h2><span className="text-[10px] px-2 py-0.5 rounded bg-cyan-950 border border-cyan-800 text-cyan-300 font-bold">PROTOTYPE</span></div><p className="text-xs text-slate-400 mt-1">Compact operational indicators derived from local demonstration data.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="bg-[#091220] border border-slate-800 rounded p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase text-slate-400">Spill Detections / Period</span><Waves className="w-4 h-4 text-cyan-400" /></div><div className="text-3xl font-bold text-cyan-400 mt-3">{mockIncidents.length}</div><div className="flex items-end gap-1 h-16 mt-3">{mockIncidents.map((incident) => <div key={incident.id} className="flex-1 bg-cyan-500/70 rounded-t" style={{ height: `${Math.max(20, incident.spillAreaKm2 * 4)}%` }} title={`${incident.spillAreaKm2} km²`} />)}</div></div><div className="bg-[#091220] border border-slate-800 rounded p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase text-slate-400">Risk Distribution</span><CircleAlert className="w-4 h-4 text-red-400" /></div><div className="space-y-2 mt-4">{riskCounts.map(({ risk, count }) => <div key={risk} className="flex items-center gap-2 text-[10px]"><span className="w-14 text-slate-400">{risk}</span><div className="h-2 flex-1 bg-slate-800 rounded overflow-hidden"><div className={`h-full ${risk === 'CRITICAL' ? 'bg-red-500' : risk === 'HIGH' ? 'bg-amber-500' : risk === 'MEDIUM' ? 'bg-yellow-500' : 'bg-emerald-500'}`} style={{ width: `${Math.max(8, count / mockIncidents.length * 100)}%` }} /></div><span className="text-slate-300">{count}</span></div>)}</div></div><div className="bg-[#091220] border border-slate-800 rounded p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase text-slate-400">Vessel Investigation Status</span><Ship className="w-4 h-4 text-amber-400" /></div><div className="text-3xl font-bold text-amber-400 mt-3">{mockVessels.filter((vessel) => vessel.isProbableSource).length}</div><p className="text-[10px] text-slate-500 mt-1">probable source candidates</p><div className="mt-4 text-xs text-slate-300">{mockVessels.filter((vessel) => vessel.isProbableSource).map((vessel) => <div key={vessel.id} className="border-t border-slate-800 pt-2 mt-2 flex justify-between"><span>{vessel.name}</span><span className="text-amber-400">92%</span></div>)}</div></div></div></div>;
};

export default AnalyticsView;
